name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          mkdir -p ${{github.workspace}}/src

      - uses: actions/checkout@v2
        with:
          path: src/ros2_rclpy_template_package

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          tags: template:humble
          file: Dockerfile
          push: false

      - name: Build
        uses: eaa3/docker-run-action@v3
        with:
          image: template:humble
          options: -v ${{github.workspace}}/:/ros/
          run: |
            cd /ros
            . /opt/ros/humble/setup.sh
            echo $(pwd)
            ls
            ls src
            colcon build

      - name: Test
        uses: eaa3/docker-run-action@v3
        with:
          image: template:humble
          options: -v ${{github.workspace}}/:/ros/
          run: |
            cd /ros
            . /opt/ros/humble/setup.sh
            . install/setup.sh
            colcon test
            colcon test-result
            
      - name: Upload Tests to Artifacts
        uses: actions/upload-artifact@v2.9.0
        if: always()
        with:
          name: test-results
          path: build/*/*.xml

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: build/*/*.xml